test11
Signed-off-by: ffais <ffais@fbk.eu>

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,189 +1,189 @@
-name: Tests
-run-name: Run tests by @${{ github.actor }}
+# name: Tests
+# run-name: Run tests by @${{ github.actor }}
 
-on:
-  push:
-    branches:
-      - main
-  pull_request:
+# on:
+#   push:
+#     branches:
+#       - main
+#   pull_request:
 
 
-env:
-  REGISTRY: ghcr.io
-  IMAGE_NAME: kubeai-project/kubeai
+# env:
+#   REGISTRY: ghcr.io
+#   IMAGE_NAME: kubeai-project/kubeai
 
-jobs:
-  build-image:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v6
+# jobs:
+#   build-image:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v6
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+#       - name: Set up Docker Buildx
+#         uses: docker/setup-buildx-action@v3
 
-      - name: Build and export kubeai
-        uses: docker/build-push-action@v6
-        with:
-          tags: ghcr.io/kubeai-project/kubeai:test
-          outputs: type=docker,dest=${{ runner.temp }}/kubeai.tar
+#       - name: Build and export kubeai
+#         uses: docker/build-push-action@v6
+#         with:
+#           tags: ghcr.io/kubeai-project/kubeai:test
+#           outputs: type=docker,dest=${{ runner.temp }}/kubeai.tar
 
-      - name: Build and export model loader
-        uses: docker/build-push-action@v6
-        with:
-          context: ./components/model-loader
-          file: ./components/model-loader/Dockerfile
-          tags: ghcr.io/kubeai-project/kubeai-model-loader:test
-          outputs: type=docker,dest=${{ runner.temp }}/model-loader.tar
+#       - name: Build and export model loader
+#         uses: docker/build-push-action@v6
+#         with:
+#           context: ./components/model-loader
+#           file: ./components/model-loader/Dockerfile
+#           tags: ghcr.io/kubeai-project/kubeai-model-loader:test
+#           outputs: type=docker,dest=${{ runner.temp }}/model-loader.tar
 
-      - name: Upload artifact
-        uses: actions/upload-artifact@v5
-        with:
-          name: docker-images
-          path: ${{ runner.temp }}/*.tar
+#       - name: Upload artifact
+#         uses: actions/upload-artifact@v5
+#         with:
+#           name: docker-images
+#           path: ${{ runner.temp }}/*.tar
 
-  unit-and-integration:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v6
+#   unit-and-integration:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v6
 
-      - name: Run unit tests
-        run: make test-unit
+#       - name: Run unit tests
+#         run: make test-unit
 
-      - name: Run integration tests
-        run: make test-integration
+#       - name: Run integration tests
+#         run: make test-integration
 
-  e2e-general:
-    runs-on: ubuntu-latest
-    needs: build-image
-    # NOTE: Uncomment if we start getting limited on number of concurrent jobs
-    # (due to rapid pushes, etc).
-    #needs: unit-and-integration # No use in running e2e tests if integration tests fail.
-    strategy:
-      matrix:
-        testcase:
-        - "quickstart"
-        - "rollouts"
-        - "openai-python-client"
-        - "autoscaler-restart-under-load"
-        - "autoscaler-restart-no-load"
-        - "cache-shared-filesystem"
-        - "engine-vllm-pvc"
-        - "engine-ollama-pvc"
-        - "model-files"
-        - "s3-model"
-        - "lora-adapter"
-        - "oci-model"
-    steps:
-      - name: Aggressive cleanup
-        if: matrix.testcase == 's3-model'
-        run: |
-          # Remove Java (JDKs)
-          sudo rm -rf /usr/lib/jvm
-          # Remove .NET SDKs
-          sudo rm -rf /usr/share/dotnet
-          # Remove Swift toolchain
-          sudo rm -rf /usr/share/swift
-          # Remove Haskell (GHC)
-          sudo rm -rf /usr/local/.ghcup
-          # Remove Julia
-          sudo rm -rf /usr/local/julia*
-          # Remove Android SDKs
-          sudo rm -rf /usr/local/lib/android
-          # Remove Chromium (optional if not using for browser tests)
-          sudo rm -rf /usr/local/share/chromium
-          # Remove Microsoft/Edge and Google Chrome builds
-          sudo rm -rf /opt/microsoft /opt/google
-          # Remove Azure CLI
-          sudo rm -rf /opt/az
-          # Remove PowerShell
-          sudo rm -rf /usr/local/share/powershell
-          docker system prune -af || true
-          docker builder prune -af || true
-          df -h
-      - name: Checkout code
-        uses: actions/checkout@v6
-      - name: Download artifact
-        uses: actions/download-artifact@v6
-        with:
-          name: docker-images
-          path: ${{ runner.temp }}
+#   e2e-general:
+#     runs-on: ubuntu-latest
+#     needs: build-image
+#     # NOTE: Uncomment if we start getting limited on number of concurrent jobs
+#     # (due to rapid pushes, etc).
+#     #needs: unit-and-integration # No use in running e2e tests if integration tests fail.
+#     strategy:
+#       matrix:
+#         testcase:
+#         - "quickstart"
+#         - "rollouts"
+#         - "openai-python-client"
+#         - "autoscaler-restart-under-load"
+#         - "autoscaler-restart-no-load"
+#         - "cache-shared-filesystem"
+#         - "engine-vllm-pvc"
+#         - "engine-ollama-pvc"
+#         - "model-files"
+#         - "s3-model"
+#         - "lora-adapter"
+#         - "oci-model"
+#     steps:
+#       - name: Aggressive cleanup
+#         if: matrix.testcase == 's3-model'
+#         run: |
+#           # Remove Java (JDKs)
+#           sudo rm -rf /usr/lib/jvm
+#           # Remove .NET SDKs
+#           sudo rm -rf /usr/share/dotnet
+#           # Remove Swift toolchain
+#           sudo rm -rf /usr/share/swift
+#           # Remove Haskell (GHC)
+#           sudo rm -rf /usr/local/.ghcup
+#           # Remove Julia
+#           sudo rm -rf /usr/local/julia*
+#           # Remove Android SDKs
+#           sudo rm -rf /usr/local/lib/android
+#           # Remove Chromium (optional if not using for browser tests)
+#           sudo rm -rf /usr/local/share/chromium
+#           # Remove Microsoft/Edge and Google Chrome builds
+#           sudo rm -rf /opt/microsoft /opt/google
+#           # Remove Azure CLI
+#           sudo rm -rf /opt/az
+#           # Remove PowerShell
+#           sudo rm -rf /usr/local/share/powershell
+#           docker system prune -af || true
+#           docker builder prune -af || true
+#           df -h
+#       - name: Checkout code
+#         uses: actions/checkout@v6
+#       - name: Download artifact
+#         uses: actions/download-artifact@v6
+#         with:
+#           name: docker-images
+#           path: ${{ runner.temp }}
 
-      - name: Load image
-        run: |
-          docker load --input ${{ runner.temp }}/kubeai.tar
-          docker load --input ${{ runner.temp }}/model-loader.tar
-          docker image ls -a
+#       - name: Load image
+#         run: |
+#           docker load --input ${{ runner.temp }}/kubeai.tar
+#           docker load --input ${{ runner.temp }}/model-loader.tar
+#           docker image ls -a
 
-      - name: Install kind
-        run: |
-          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.31.0/kind-linux-amd64
-          chmod +x ./kind
-          sudo mv ./kind /usr/local/bin/kind
+#       - name: Install kind
+#         run: |
+#           curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.31.0/kind-linux-amd64
+#           chmod +x ./kind
+#           sudo mv ./kind /usr/local/bin/kind
 
-      - name: Install helm
-        run: |
-          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
-          chmod 700 get_helm.sh
-          ./get_helm.sh
+#       - name: Install helm
+#         run: |
+#           curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
+#           chmod 700 get_helm.sh
+#           ./get_helm.sh
 
-      - name: Start kind cluster
-        run: kind create cluster
+#       - name: Start kind cluster
+#         run: kind create cluster
 
-      - name: Load kubeai image in KinD
-        run: |
-          kind load docker-image ghcr.io/kubeai-project/kubeai:test
-          kind load docker-image ghcr.io/kubeai-project/kubeai-model-loader:test
+#       - name: Load kubeai image in KinD
+#         run: |
+#           kind load docker-image ghcr.io/kubeai-project/kubeai:test
+#           kind load docker-image ghcr.io/kubeai-project/kubeai-model-loader:test
 
-      - name: Run the e2e testcase
-        run: make test-e2e TEST_CASE=${{ matrix.testcase }}
+#       - name: Run the e2e testcase
+#         run: make test-e2e TEST_CASE=${{ matrix.testcase }}
 
-  e2e-engines:
-    runs-on: ubuntu-latest
-    needs: build-image
-    # NOTE: Uncomment if we start getting limited on number of concurrent jobs
-    # (due to rapid pushes, etc).
-    #needs: unit-and-integration # No use in running e2e tests if integration tests fail.
-    strategy:
-      matrix:
-        engine: ["fasterwhisper", "infinity"] # "VLLM", "OLlama"
-        # Run each test case with and without caching.
-        cacheProfile: ["", "e2e-test-kind-pv"]
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v6
+#   e2e-engines:
+#     runs-on: ubuntu-latest
+#     needs: build-image
+#     # NOTE: Uncomment if we start getting limited on number of concurrent jobs
+#     # (due to rapid pushes, etc).
+#     #needs: unit-and-integration # No use in running e2e tests if integration tests fail.
+#     strategy:
+#       matrix:
+#         engine: ["fasterwhisper", "infinity"] # "VLLM", "OLlama"
+#         # Run each test case with and without caching.
+#         cacheProfile: ["", "e2e-test-kind-pv"]
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v6
 
-      - name: Download artifact
-        uses: actions/download-artifact@v6
-        with:
-          name: docker-images
-          path: ${{ runner.temp }}
+#       - name: Download artifact
+#         uses: actions/download-artifact@v6
+#         with:
+#           name: docker-images
+#           path: ${{ runner.temp }}
 
-      - name: Load image
-        run: |
-          docker load --input ${{ runner.temp }}/kubeai.tar
-          docker load --input ${{ runner.temp }}/model-loader.tar
-          docker image ls -a
-      - name: Install kind
-        run: |
-          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.30.0/kind-linux-amd64
-          chmod +x ./kind
-          sudo mv ./kind /usr/local/bin/kind
+#       - name: Load image
+#         run: |
+#           docker load --input ${{ runner.temp }}/kubeai.tar
+#           docker load --input ${{ runner.temp }}/model-loader.tar
+#           docker image ls -a
+#       - name: Install kind
+#         run: |
+#           curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.30.0/kind-linux-amd64
+#           chmod +x ./kind
+#           sudo mv ./kind /usr/local/bin/kind
 
-      - name: Install helm
-        run: |
-          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
-          chmod 700 get_helm.sh
-          ./get_helm.sh
+#       - name: Install helm
+#         run: |
+#           curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
+#           chmod 700 get_helm.sh
+#           ./get_helm.sh
 
-      - name: Start kind cluster
-        run: kind create cluster
+#       - name: Start kind cluster
+#         run: kind create cluster
 
-      - name: Load kubeai image in KinD
-        run: |
-          kind load docker-image ghcr.io/kubeai-project/kubeai:test
-          kind load docker-image ghcr.io/kubeai-project/kubeai-model-loader:test
+#       - name: Load kubeai image in KinD
+#         run: |
+#           kind load docker-image ghcr.io/kubeai-project/kubeai:test
+#           kind load docker-image ghcr.io/kubeai-project/kubeai-model-loader:test
 
-      - name: Run the e2e testcase
-        run: make test-e2e TEST_CASE=engine-${{ matrix.engine }} CACHE_PROFILE=${{ matrix.cacheProfile }}
+#       - name: Run the e2e testcase
+#         run: make test-e2e TEST_CASE=engine-${{ matrix.engine }} CACHE_PROFILE=${{ matrix.cacheProfile }}
